### PR TITLE
allow scrolling on tabs that contain tables

### PR DESCRIPTION
**Pull request by bruncun**

### CODE REVIEW

**Comment by qtrandev** [comment]
The first commit "allow scrolling on tabs that contain tables" looks good, but the second for #37 didn't seem to change it.

**Comment by qtrandev** [comment]
If you want, I can merge the first commit in.

**Comment by bruncun** [comment]
The second commit was a second hot fix I added. Currently, on mobile, nav items on click do not hide the menu. This is default bootstrap behavior for fixed navigations, but I don't think it's well suited for our use case. The second commit solves this issue.

**Comment by qtrandev** [comment]
With the 2 commits applied, selecting a nav item doesn't hide the menu so I don't see a difference. Also, when the page loads, it should not automatically show the menu.

**Comment by bruncun** [comment]
Resolved the issue, while refactoring I accidentally missed a set of parentheses. Tested and is working again.

**Comment by qtrandev** [comment]
Manually cherry-picked the 3 commits. This is now completed.

**Pull request closed without merging**
